//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranetPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_UserRole
    {
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public int UserRoleID { get; set; }
    
        public virtual CMS_Role CMS_Role { get; set; }
        public virtual CMS_User CMS_User { get; set; }
    }
}
