//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranetPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_Role()
        {
            this.CMS_UserRole = new HashSet<CMS_UserRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleDisplayName { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<int> SiteID { get; set; }
        public System.Guid RoleGUID { get; set; }
        public System.DateTime RoleLastModified { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public Nullable<bool> RoleIsGroupAdministrator { get; set; }
        public Nullable<bool> RoleIsDomain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_UserRole> CMS_UserRole { get; set; }
    }
}
