//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranetPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_User()
        {
            this.CMS_UserRole = new HashSet<CMS_UserRole>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string UserPassword { get; set; }
        public string PreferredCultureCode { get; set; }
        public string PreferredUICultureCode { get; set; }
        public bool UserEnabled { get; set; }
        public Nullable<bool> UserIsExternal { get; set; }
        public string UserPasswordFormat { get; set; }
        public Nullable<System.DateTime> UserCreated { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public string UserStartingAliasPath { get; set; }
        public System.Guid UserGUID { get; set; }
        public System.DateTime UserLastModified { get; set; }
        public string UserLastLogonInfo { get; set; }
        public Nullable<bool> UserIsHidden { get; set; }
        public string UserVisibility { get; set; }
        public Nullable<bool> UserIsDomain { get; set; }
        public Nullable<bool> UserHasAllowedCultures { get; set; }
        public Nullable<bool> UserMFRequired { get; set; }
        public int UserPrivilegeLevel { get; set; }
        public string UserSecurityStamp { get; set; }
        public byte[] UserMFSecret { get; set; }
        public Nullable<long> UserMFTimestep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_UserRole> CMS_UserRole { get; set; }
    }
}
